# Generated by Django 4.2.3 on 2023-07-08 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False)),
                ('telephoneNumber', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.address')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.userprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
