# Generated by Django 4.2.2 on 2023-07-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='total',
        ),
    ]
