# Generated by Django 4.2.3 on 2023-07-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_userprofile_alter_order_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
