# Generated by Django 4.2.3 on 2023-07-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
